### PR TITLE
Remove keyword detection

### PR DESCRIPTION
**Pull request by davidfischer**
Now that topic detection happens on the ad server, the ad client doesn't need to do keyword detection

### CODE REVIEW

**Comment by davidfischer** [comment]
The docs CI issue is fixed in https://github.com/readthedocs/ethical-ad-client/pull/158.

**Review by ericholscher — APPROVED** [review]
Glad to be done with this hacky approach :)

Just to confirm, this will still send along the publisher-defined ones on RTD sites right?

Looks like we're just setting these on data-ea-keywords, so should be fine there:

**Review by ericholscher — APPROVED** [review]
Glad to be done with this hacky approach :)

Just to confirm, this will still send along the publisher-defined ones on RTD sites right?

Looks like we're just setting these on data-ea-keywords, so should be fine there:
https://github.com/readthedocs/readthedocs.org/blob/main/readthedocs/core/static-src/core/js/doc-embed/sponsorship.js#L182C19-L185

This will limit our inventory of longer tail keywords for campaigns that are actually doing keyword-specific targeting, instead of ML-based targeting, but I think that's mostly OK, since those keywords probably weren't super valuable anyway?

**Comment by davidfischer** [comment]
For now due to sites we can't parse with our backend parser, we're going to leave this for now.

**Pull request closed without merging**
