### PR TITLE
FixedFooter: use a bigger `z-index`

### PR DESCRIPTION
**Pull request by humitos**
We need a bigger `z-index` than `199` to show the ad over the Read the Docs Sphinx Theme navigation bar.

### Without this PR

Screenshot_2023-08-28_16-39-55

### With this PR

Screenshot_2023-08-28_16-40-19

----

Note that I'm not sure how this project has to be built or tested, so I did this manually but I'm not sure these changes are correct.

### CODE REVIEW

**Review by davidfischer — APPROVED** [review]
Thanks for this. This should improve things for RTD and hopefully doesn't cause issues with other people's sites.

**Comment by davidfischer** [comment]
The CI issue is just because we have a check that the built assets match what would be built.

**Comment by humitos** [comment]
I will run `npm run build` and make a push to fix that.

**Comment by humitos** [comment]
Ups... I'm getting an error when running that command. Maybe the version of node I'm using (`v18.15.0`) is not the correct one?

**Comment by davidfischer** [comment]
That's most likely the issue. I can just run it. I'm running node v14.

**Comment by humitos** [comment]
Should I just merge this PR or should I do something else here?

**Comment by humitos** [comment]
BTW, using node v14.18.1 fails also locally for me -- with a different error, tho 😄

**Comment by davidfischer** [comment]
I'm on v14.19.0. When you do switch node versions, you may need to re-install the node modules as some of the ones that compile saas are native.

**Comment by humitos** [comment]
I'll try that

**Comment by humitos** [comment]
That worked!

**Pull request merged**
